# Generated by Django 3.2.6 on 2021-08-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irdp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Ahli',
        ),
        migrations.AlterModelOptions(
            name='ahli',
            options={'verbose_name_plural': 'Ahli-ahli'},
        ),
    ]
