# Generated by Django 3.2.6 on 2021-08-20 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('irdp', '0002_auto_20210820_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahli',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ahli',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ahli',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ahli',
            name='state',
            field=models.CharField(max_length=55),
        ),
    ]
