# Generated by Django 3.2.6 on 2021-08-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irdp', '0003_auto_20210820_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahli',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='ahli',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ahli',
            name='state',
            field=models.TextField(),
        ),
    ]
